set(_AMENT_PACKAGE_NAME "customservices")
set(customservices_VERSION "0.0.0")
set(customservices_MAINTAINER "pmlab <juyue0835@gmail.com>")
set(customservices_BUILD_DEPENDS "rosidl_default_generators")
set(customservices_BUILDTOOL_DEPENDS "ament_cmake")
set(customservices_BUILD_EXPORT_DEPENDS )
set(customservices_BUILDTOOL_EXPORT_DEPENDS )
set(customservices_EXEC_DEPENDS "rosidl_default_runtime")
set(customservices_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(customservices_GROUP_DEPENDS )
set(customservices_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(customservices_DEPRECATED "")
set(customservices_EXPORT_TAGS)
list(APPEND customservices_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
