set(_AMENT_PACKAGE_NAME "dotnet_cmake_module")
set(dotnet_cmake_module_VERSION "0.0.0")
set(dotnet_cmake_module_MAINTAINER "Esteve Fernandez <esteve@osrfoundation.org>")
set(dotnet_cmake_module_BUILD_DEPENDS )
set(dotnet_cmake_module_BUILDTOOL_DEPENDS "ament_cmake")
set(dotnet_cmake_module_BUILD_EXPORT_DEPENDS )
set(dotnet_cmake_module_BUILDTOOL_EXPORT_DEPENDS )
set(dotnet_cmake_module_EXEC_DEPENDS )
set(dotnet_cmake_module_TEST_DEPENDS )
set(dotnet_cmake_module_GROUP_DEPENDS )
set(dotnet_cmake_module_MEMBER_OF_GROUPS )
set(dotnet_cmake_module_DEPRECATED "")
set(dotnet_cmake_module_EXPORT_TAGS)
list(APPEND dotnet_cmake_module_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
